### ISSUE TITLE
CUBLAS_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by bianjilong** [DeepMotionAIResearch/DenseMatchingBenchmark#20]
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
Exception raised from createCublasHandle at /opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/cuda/CublasHandlePool.cpp:8 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x2ba39fce177d in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xcfc185 (0x2ba36e74d185 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #2: at::cuda::getCurrentCUDABlasHandle() + 0xb75 (0x2ba36e74e065 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xcef217 (0x2ba36e740217 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: at::native::(anonymous namespace)::slow_conv_transpose3d_backward_out_cuda_template(at::Tensor const&, at::Tensor const&, at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>) + 0x15ef (0x2ba36fb374ef in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: at::native::slow_conv_transpose3d_backward_cuda(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x20d (0x2ba36fb3b8ed in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xd24ad9 (0x2ba36e775ad9 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xd424f7 (0x2ba36e7934f7 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #8: at::slow_conv_transpose3d_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x2b1 (0x2ba367eed7e1 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x2c6dc1e (0x2ba369bfec1e in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0xe6ff97 (0x2ba367e00f97 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: at::slow_conv_transpose3d_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, std::array<bool, 3ul>) + 0x2b1 (0x2ba367eed7e1 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: torch::autograd::generated::SlowConvTranspose3DBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x39b (0x2ba369a4a0db in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x30d1017 (0x2ba36a062017 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1400 (0x2ba36a05d860 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x451 (0x2ba36a05e401 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x89 (0x2ba36a056579 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #17: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x4a (0x2ba365fc399a in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #18: <unknown function> + 0xc819d (0x2ba363b2e19d in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #19: <unknown function> + 0x7ea5 (0x2ba344879ea5 in /lib64/libpthread.so.0)
frame #20: clone + 0x6d (0x2ba344b8c8dd in /lib64/libc.so.6)

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1595629403081/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x2ba39fce177d in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xb5d (0x2ba39fa7dd9d in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x2ba39fccdb1d in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x7aa1b9 (0x2ba36773b1b9 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x2ad69f3 (0x2ba369a679f3 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x30d1592 (0x2ba36a062592 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x2ba36a06263f in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3ded39 (0x2ba365e77d39 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: c10::TensorImpl::release_resources() + 0x20 (0x2ba39fccdaf0 in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x53f0ea (0x2ba365fd80ea in /N/u/jibian/Carbonate/.conda/envs/dense_matching_benchmark/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #25: __libc_start_main + 0xf5 (0x2ba344ab0555 in /lib64/libc.so.6)

Aborted

**Comment by youmi-zym** [comment]
Please output the system info with code below:

```
from torch.utils.collect_env import get_pretty_env_info
print(get_pretty_env_info())
```


But in my experience, it may result from:
1. 2080Ti series GPU, but 1080Ti is OK;
2. Pytorch Version, torch <=1.4 is OK.

**Comment by youmi-zym** [comment]
Hi, today I find the same problem, I solved it by adding `find_unused_parameters=True` to the config file. Hope it works for you.
